export const PACKAGES_DATA = [
  {
    slug: 'basic-health-checkup',
    id: 1, name: 'Basic Health Checkup', emoji: '🌱',
    tagline: 'Your Health Journey Starts Here',
    ageGroup: 'All Ages', gender: 'all', tests: 84,
    market: 4000, offer: 999, savings: 3001,
    color: '#10b981', gradFrom: '#10b981', gradTo: '#059669',
    badge: 'MOST POPULAR',
    heroLine: 'Know Your Numbers. Live Better.',
    whyNow: "Most people don't know their cholesterol, blood sugar, or thyroid levels until something goes wrong. This package gives you a complete baseline — so you can catch problems early and stay ahead of your health.",
    targetedMessage: "Think of this as your annual health report card. Simple, fast, and covers all the essentials — blood, organs, thyroid, kidneys. Done at home, results in 24 hours.",
    funFacts: [
      { emoji: '❤️', fact: '1 in 4 Indians has hidden thyroid issues — most don\'t know it' },
      { emoji: '🩸', fact: 'Anemia affects 58% of Indian women — easily detected with CBC' },
      { emoji: '🦴', fact: 'Vitamin D deficiency affects 70% of urban Indians' },
      { emoji: '🫁', fact: 'Early kidney issues show NO symptoms — only blood tests reveal them' },
    ],
    profiles: [
      { name: 'Blood Glucose Fasting', tests: 1, icon: '🩸', why: 'Screens for pre-diabetes and diabetes — the silent epidemic' },
      { name: 'Thyroid Profile (T3, T4, TSH)', tests: 3, icon: '🦋', why: 'Thyroid controls your energy, weight, and mood — check it annually' },
      { name: 'Heart Risk Profile (Lipid)', tests: 9, icon: '❤️', why: 'Cholesterol levels predict heart disease risk years before symptoms appear' },
      { name: 'Liver Function Test (LFT)', tests: 12, icon: '🫀', why: 'Your liver filters 1 litre of blood per minute — make sure it\'s healthy' },
      { name: 'Kidney Function Test (Basic)', tests: 6, icon: '🫘', why: 'Kidneys clean your blood 200 times daily — silent damage shows here first' },
      { name: 'Complete Urine Routine (CUE)', tests: 20, icon: '💧', why: 'Urine reveals kidney health, infections, and diabetes markers' },
      { name: 'Complete Blood Count (CBC)', tests: 25, icon: '🔴', why: 'Detects anaemia, infections, and blood disorders comprehensively' },
      { name: 'Iron Studies (Anaemia Screen)', tests: 5, icon: '⚡', why: 'Iron deficiency causes fatigue, brain fog — extremely common in India' },
      { name: 'Healthy Bone Profile', tests: 3, icon: '🦴', why: 'Calcium & Vitamin D — essential for strong bones at every age' },
    ],
    symptoms: ['Unexplained fatigue', 'Weight changes', 'Brain fog', 'Frequent urination', 'Hair loss'],
    cta: 'Start Your Health Journey',
  },
  {
    slug: 'complete-health-checkup',
    id: 2, name: 'Complete Health Checkup', emoji: '⚡',
    tagline: 'Level Up Your Health Game',
    ageGroup: '20 to 34 Years', gender: 'all', tests: 89,
    market: 6500, offer: 1399, savings: 5101,
    color: '#3b82f6', gradFrom: '#3b82f6', gradTo: '#2563eb',
    badge: 'BEST VALUE',
    heroLine: 'Your 20s & 30s Decide Your Future Health.',
    whyNow: "The habits and health markers you establish in your 20s and 30s predict your health for the next 40 years. Diabetes, heart disease, and vitamin deficiencies start silently long before symptoms appear. This is your complete health baseline.",
    targetedMessage: "You're young, busy, maybe eating takeout, skipping sleep. This package checks everything that your lifestyle affects — sugar, cholesterol, vitamins, liver, kidneys, thyroid. All 89 parameters, done at home, under ₹1400.",
    funFacts: [
      { emoji: '🍕', fact: 'Unhealthy diet in your 20s raises heart disease risk by 40% by age 40' },
      { emoji: '😴', fact: 'Poor sleep raises blood sugar — checked by HbA1c in this package' },
      { emoji: '💪', fact: 'Vitamin B12 deficiency causes muscle weakness — affects 47% of young Indians' },
      { emoji: '📱', fact: 'Screen time & blue light affect thyroid — TSH in this package catches it' },
    ],
    profiles: [
      { name: 'Diabetes Screening (Glucose + HbA1c)', tests: 2, icon: '🍬', why: 'HbA1c shows your 3-month average sugar — the gold standard for diabetes screening' },
      { name: 'Thyroid Profile (T3, T4, TSH)', tests: 3, icon: '🦋', why: 'Thyroid issues cause weight gain, fatigue, anxiety — extremely common in young adults' },
      { name: 'Heart Risk Profile (Lipid)', tests: 9, icon: '❤️', why: 'Bad cholesterol starts building in your 20s — catch it before it causes damage' },
      { name: 'Liver Function Test (LFT)', tests: 12, icon: '🫀', why: 'Alcohol, junk food, and medications stress your liver — check its health' },
      { name: 'Kidney Function Test (Basic)', tests: 6, icon: '🫘', why: 'Dehydration and high-protein diets affect kidneys — this catches early damage' },
      { name: 'Complete Urine Routine (CUE)', tests: 20, icon: '💧', why: 'Comprehensive kidney and bladder health screen' },
      { name: 'Complete Blood Count (CBC)', tests: 25, icon: '🔴', why: 'Detects anaemia, viral infections, and immune issues' },
      { name: 'Vital Vitamins Profile (D & B12)', tests: 5, icon: '☀️', why: 'D & B12 deficiency causes depression, fatigue, bone pain — affects 7 in 10 urban Indians' },
      { name: 'Iron Studies (Anaemia Screen)', tests: 5, icon: '⚡', why: 'Iron deficiency is the #1 nutritional deficiency worldwide' },
      { name: 'Healthy Bone Profile', tests: 3, icon: '🦴', why: 'Build bone mass now — peak bone density is reached by age 30' },
    ],
    symptoms: ['Constant tiredness', 'Weight gain despite diet', 'Mood swings', 'Skin problems', 'Poor sleep'],
    cta: 'Invest in Your Future Health',
  },
  {
    slug: 'male-health-package',
    id: 3, name: 'Male Health Package', emoji: '💪',
    tagline: 'Real Men Get Tested. Real Men Stay Strong.',
    ageGroup: '35 to 60 Years', gender: 'male', tests: 112,
    market: 12000, offer: 2999, savings: 9001,
    color: '#1B4D3E', gradFrom: '#1B4D3E', gradTo: '#2d6b60',
    badge: 'PREMIUM',
    heroLine: 'You Take Care of Everyone. Who Takes Care of You?',
    whyNow: "After 35, men face rapidly rising risks of heart disease, diabetes, and hormonal changes. Indian men are 2x more likely to die from preventable diseases than women — largely because they skip health checks. This package covers everything that matters for a man aged 35-60.",
    targetedMessage: "You fix the car, the finances, the family problems. But when did you last fix yourself? This 112-test package covers your heart, liver, kidneys, hormones, sugar, vitamins, and more. Done at home. Results in 24 hours.",
    funFacts: [
      { emoji: '💔', fact: 'Heart disease is the #1 killer of Indian men above 40' },
      { emoji: '🍺', fact: 'Even moderate drinking raises liver enzyme levels — detected by LFT' },
      { emoji: '😤', fact: 'Work stress raises cortisol which raises blood sugar — checked here' },
      { emoji: '🏋️', fact: 'Low testosterone affects 1 in 4 men over 40 — causes fatigue & weight gain' },
    ],
    profiles: [
      { name: 'Complete Diabetes Monitoring', tests: 7, icon: '🍬', why: 'Men develop diabetes 5 years earlier than women on average — full monitoring critical' },
      { name: 'Heart Risk Profile (Lipid)', tests: 9, icon: '❤️', why: 'Indian men have 50% higher cardiac risk than Western men at the same age' },
      { name: 'Liver Function Test (LFT)', tests: 12, icon: '🫀', why: 'Fatty liver affects 1 in 3 Indian men over 35 — usually with no symptoms' },
      { name: 'Kidney Function Test (Basic)', tests: 6, icon: '🫘', why: 'High protein intake and low water intake strain kidneys — caught here early' },
      { name: 'Complete Blood Count (CBC)', tests: 25, icon: '🔴', why: 'Complete blood picture including RBC, WBC, platelets, and haemoglobin' },
      { name: 'Thyroid + FT3 + FT4 (Full)', tests: 5, icon: '🦋', why: 'Thyroid issues in men are underdiagnosed — affects metabolism and energy' },
      { name: 'Electrolyte Profile', tests: 4, icon: '⚡', why: 'Sodium, Potassium imbalance causes muscle cramps, fatigue, heart rhythm issues' },
      { name: 'Arthritis Screen (RA-Factor)', tests: 4, icon: '🦴', why: 'Early arthritis detection before joint damage — especially for desk workers' },
      { name: 'Vital Vitamins (D & B12)', tests: 7, icon: '☀️', why: 'Both critical for muscle strength, nerve health, and immunity' },
      { name: 'Infection Screening (Hepatitis + ESR)', tests: 3, icon: '🛡️', why: 'Silent hepatitis B & C infections affect millions of Indian men' },
      { name: 'Insulin Fasting', tests: 1, icon: '💉', why: 'Insulin resistance precedes diabetes by 10 years — catch it early' },
      { name: 'Folate / Vitamin B9', tests: 1, icon: '🌿', why: 'B9 essential for DNA repair and sperm health' },
      { name: 'Peripheral Blood Smear', tests: 1, icon: '🔬', why: 'Detects blood cell abnormalities not visible in routine CBC' },
      { name: 'Urine Analysis (CUE)', tests: 20, icon: '💧', why: 'Complete kidney and urinary tract health screen' },
      { name: 'Urinary Electrolyte Profile', tests: 3, icon: '🧪', why: 'Kidney\'s electrolyte handling — important for hypertension monitoring' },
      { name: 'Iron Studies', tests: 5, icon: '🩸', why: 'Iron overload is more common in men than women — can damage organs' },
    ],
    symptoms: ['Low energy', 'Belly weight gain', 'Poor sleep', 'Reduced stamina', 'Joint pain', 'High stress'],
    cta: 'Take Charge of Your Health',
  },
  {
    slug: 'female-health-package',
    id: 4, name: 'Female Health Package', emoji: '🌸',
    tagline: 'She Does Everything. Let\'s Make Sure She\'s Okay.',
    ageGroup: '35 to 60 Years', gender: 'female', tests: 112,
    market: 12000, offer: 2999, savings: 9001,
    color: '#ec4899', gradFrom: '#ec4899', gradTo: '#db2777',
    badge: 'PREMIUM',
    heroLine: 'A Woman\'s Body is Extraordinary. Treat It That Way.',
    whyNow: "Between 35 and 60, women navigate perimenopause, hormonal shifts, thyroid changes, bone density loss, and rising cardiac risk — often while managing careers, families, and everyone else's health. This 112-test package is designed specifically for you.",
    targetedMessage: "You notice every change in your body. This package gives you the science behind those changes — hormones, thyroid, cancer markers, heart, liver, kidneys, vitamins. Comprehensive. Empowering. Done at home, because your time matters.",
    funFacts: [
      { emoji: '🦋', fact: 'Women are 5-8x more likely than men to develop thyroid disorders' },
      { emoji: '🩺', fact: 'Ovarian cancer has no early symptoms — CA125 in this package screens for it' },
      { emoji: '🦴', fact: 'Women lose 20% of bone density in the 5-7 years after menopause' },
      { emoji: '❤️', fact: 'Heart disease is the leading cause of death in Indian women over 45' },
    ],
    profiles: [
      { name: 'Complete Diabetes Monitoring', tests: 7, icon: '🍬', why: 'Gestational diabetes history raises lifetime diabetes risk — monitor closely' },
      { name: 'Heart Risk Profile (Lipid)', tests: 9, icon: '❤️', why: 'Post-35, women\'s cardiac risk rises significantly — estrogen protection decreases' },
      { name: 'Liver Function Test (LFT)', tests: 12, icon: '🫀', why: 'Hormonal contraceptives can affect liver — regular monitoring essential' },
      { name: 'Kidney Function Test (Basic)', tests: 6, icon: '🫘', why: 'UTIs are 50x more common in women — kidney health monitoring critical' },
      { name: 'Complete Blood Count (CBC)', tests: 25, icon: '🔴', why: 'Menstrual blood loss makes anaemia extremely common — catch it early' },
      { name: 'Thyroid + FT3 + FT4 (Full)', tests: 5, icon: '🦋', why: 'Thyroid is the control center of women\'s health — weight, mood, fertility, energy' },
      { name: 'CA125 — Ovarian Cancer Marker', tests: 1, icon: '🎗️', why: 'Ovarian cancer is often detected too late — this early marker screen is vital' },
      { name: 'Hormonal Profile (LH, FSH, Prolactin)', tests: 3, icon: '🌸', why: 'Tracks perimenopause, PCOS, and fertility health comprehensively' },
      { name: 'Arthritis Screen (RA-Factor)', tests: 4, icon: '🦴', why: 'Rheumatoid arthritis is 3x more common in women — early detection matters' },
      { name: 'Vital Vitamins (D & B12)', tests: 7, icon: '☀️', why: 'Critical for bone health, nerve function, energy, and mood regulation' },
      { name: 'Iron Studies', tests: 5, icon: '🩸', why: 'Iron deficiency anaemia affects 57% of Indian women — this catches it completely' },
      { name: 'Infection Screening (Hepatitis + ESR)', tests: 3, icon: '🛡️', why: 'ESR is an inflammation marker — elevated in autoimmune conditions common in women' },
      { name: 'Insulin Fasting + Folate', tests: 2, icon: '💉', why: 'PCOS and insulin resistance are strongly linked — folate critical for cell health' },
      { name: 'Peripheral Blood Smear', tests: 1, icon: '🔬', why: 'Detailed blood cell analysis beyond standard CBC' },
      { name: 'Urine Analysis (CUE)', tests: 20, icon: '💧', why: 'Comprehensive urinary tract and kidney health screen' },
      { name: 'Electrolyte Profile', tests: 4, icon: '⚡', why: 'Hormonal changes affect electrolyte balance — monitored here' },
    ],
    symptoms: ['Irregular periods', 'Hot flashes', 'Fatigue', 'Mood changes', 'Hair thinning', 'Weight changes'],
    cta: 'Invest in Yourself Today',
  },
  {
    slug: 'couple-health-package',
    id: 9, name: 'Couple Health Package', emoji: '💑',
    tagline: 'Healthy Together. Happy Together.',
    ageGroup: '35 to 60 Years (Couple)', gender: 'couple', tests: 224,
    market: 24000, offer: 4499, savings: 19501,
    color: '#F4B942', gradFrom: '#d4971a', gradTo: '#F4B942',
    badge: '🔥 NEW — COUPLE',
    heroLine: 'The Couple That Gets Tested Together, Stays Healthier Together.',
    whyNow: "224 tests covering both partners completely — all 112 tests from the Male package AND all 112 tests from the Female package. At ₹4,499 for TWO people, that's just ₹2,250 per person. Same home collection visit. Same report day.",
    targetedMessage: "Book one appointment. One phlebotomist visit. Both partners get their complete health picture on the same day. Compare results, support each other, and make health decisions together. The best gift you can give each other.",
    funFacts: [
      { emoji: '💕', fact: 'Couples who track health together are 40% more likely to maintain healthy habits' },
      { emoji: '🏥', fact: 'Spouses of diabetics have 26% higher risk of developing diabetes themselves' },
      { emoji: '💰', fact: 'At ₹4,499 for 224 tests, that\'s just ₹20 per test — cheaper than a chai!' },
      { emoji: '🏠', fact: 'One home visit, one day, two complete health pictures — maximum convenience' },
    ],
    profiles: [
      { name: 'Complete Diabetes Monitoring — BOTH', tests: 14, icon: '🍬', why: 'Partners share food habits — screen both for blood sugar and insulin resistance' },
      { name: 'Heart Risk Profile — BOTH', tests: 18, icon: '❤️', why: 'Couples share stress and lifestyle — cardiac risk affects both equally' },
      { name: 'Liver Function Test — BOTH', tests: 24, icon: '🫀', why: 'Shared diet means shared liver health risks — both get comprehensive LFT' },
      { name: 'Kidney Function Test — BOTH', tests: 12, icon: '🫘', why: 'Hydration habits and diet affect kidneys — both partners screened' },
      { name: 'Complete Blood Count — BOTH', tests: 50, icon: '🔴', why: 'Complete blood health picture for both partners' },
      { name: 'Full Thyroid Profile — BOTH', tests: 10, icon: '🦋', why: 'Thyroid disorders are hereditary — screen both partners thoroughly' },
      { name: 'Hormonal Profile (Female)', tests: 3, icon: '🌸', why: 'LH, FSH, Prolactin — complete hormonal snapshot for the female partner' },
      { name: 'CA125 Ovarian Cancer Marker (Female)', tests: 1, icon: '🎗️', why: 'Critical early cancer screening exclusive to the female partner' },
      { name: 'Arthritis Screen — BOTH', tests: 8, icon: '🦴', why: 'RA factor screening for both — joint health for active couple years' },
      { name: 'Vital Vitamins D & B12 — BOTH', tests: 14, icon: '☀️', why: 'Shared indoor lifestyle — both likely deficient in D & B12' },
      { name: 'Iron Studies — BOTH', tests: 10, icon: '🩸', why: 'Iron deficiency comprehensive screen for both partners' },
      { name: 'Infection Screening — BOTH', tests: 6, icon: '🛡️', why: 'Hepatitis B & C, ESR inflammation markers for both partners' },
      { name: 'Insulin Fasting + Folate — BOTH', tests: 4, icon: '💉', why: 'Insulin resistance early detection and B9 for both partners' },
      { name: 'Urine Analysis — BOTH', tests: 40, icon: '💧', why: 'Complete urinary and kidney health for both partners' },
      { name: 'Electrolyte Profile — BOTH', tests: 8, icon: '⚡', why: 'Sodium, Potassium, Chloride levels for both partners' },
      { name: 'Peripheral Blood Smear — BOTH', tests: 2, icon: '🔬', why: 'Detailed blood cell morphology for both partners' },
    ],
    symptoms: ['Both feeling tired', 'Weight gain together', 'Shared stress', 'Planning ahead', 'Family health history'],
    cta: 'Book for Both of You',
  },
  {
    slug: 'teen-boys-package',
    id: 5, name: 'Teen Boys Package', emoji: '🏃',
    tagline: 'Grow Strong. Know Your Body.',
    ageGroup: '13 to 19 Years', gender: 'male-teen', tests: 96,
    market: 9000, offer: 2250, savings: 6750,
    color: '#f59e0b', gradFrom: '#f59e0b', gradTo: '#d97706',
    badge: 'FOR TEENS',
    heroLine: 'Your Body is Changing. Make Sure It\'s Changing Right.',
    whyNow: "The teenage years are when testosterone kicks in, growth plates close, muscles develop, and lifelong health habits form. This package checks your hormones, blood sugar, vitamins, and bone health — everything that matters as you level up from boy to man.",
    targetedMessage: "Hey! You're going through a massive transformation. Your body is doing incredible things — but it needs the right fuel and balance. This test checks your hormones (yes, testosterone!), your iron for gym performance, your vitamins for brain focus, and your sugar and heart health. It's like a full service for your body.",
    funFacts: [
      { emoji: '💪', fact: 'Testosterone peaks in your late teens — this package tracks if it\'s at optimal levels' },
      { emoji: '🍔', fact: 'Teen junk food habits raise cholesterol that stays high for life' },
      { emoji: '📚', fact: 'Vitamin B12 deficiency affects focus, memory, and exam performance' },
      { emoji: '🏋️', fact: 'Iron deficiency reduces gym performance by up to 30%' },
    ],
    profiles: [
      { name: 'Testosterone Level', tests: 1, icon: '💪', why: 'The primary male hormone — tracks healthy development during teenage years' },
      { name: 'Diabetes Screening (Glucose + HbA1c)', tests: 2, icon: '🍬', why: 'Teen obesity is rising — early diabetes detection is critical' },
      { name: 'Heart Risk Profile (Lipid)', tests: 9, icon: '❤️', why: 'Bad cholesterol from junk food diet starts accumulating in teens' },
      { name: 'Liver Function Test (LFT)', tests: 12, icon: '🫀', why: 'Protein supplements and energy drinks stress young livers' },
      { name: 'Kidney Function Test (Basic)', tests: 6, icon: '🫘', why: 'High protein, sports drinks, and dehydration affect teen kidneys' },
      { name: 'Complete Blood Count (CBC)', tests: 25, icon: '🔴', why: 'Complete blood health — essential for athletic performance and growth' },
      { name: 'Hormones: LH, FSH, TSH', tests: 3, icon: '🧬', why: 'Growth and reproductive hormones — tracks healthy teen development' },
      { name: 'Vital Vitamins (D & B12)', tests: 2, icon: '☀️', why: 'Screen time keeps teens indoors — D deficiency affects growth and mood' },
      { name: 'Iron Studies (Anaemia)', tests: 5, icon: '⚡', why: 'Iron is essential for energy, sports performance, and brain function' },
      { name: 'Electrolyte Profile', tests: 4, icon: '🧪', why: 'Sports activity causes electrolyte loss — monitor sodium and potassium' },
      { name: 'Healthy Bone Profile', tests: 3, icon: '🦴', why: 'Peak bone density is built in teen years — foundation for life' },
      { name: 'Insulin Fasting', tests: 1, icon: '💉', why: 'Insulin resistance in teens leads to adult diabetes' },
      { name: 'Urine Analysis (CUE)', tests: 20, icon: '💧', why: 'Complete urinary health and early kidney function screen' },
      { name: 'Folate / Vitamin B9', tests: 1, icon: '🌿', why: 'Critical for DNA synthesis, growth, and brain development' },
    ],
    symptoms: ['Always tired', 'Poor gym results', 'Difficulty focusing', 'Slow growth', 'Mood swings'],
    cta: 'Level Up Your Health',
  },
  {
    slug: 'teen-girls-package',
    id: 6, name: 'Teen Girls Package', emoji: '🌺',
    tagline: 'Girl, You Deserve to Know Your Body.',
    ageGroup: '13 to 19 Years', gender: 'female-teen', tests: 96,
    market: 9000, offer: 2250, savings: 6750,
    color: '#8b5cf6', gradFrom: '#8b5cf6', gradTo: '#7c3aed',
    badge: 'FOR TEENS',
    heroLine: 'Your Body. Your Power. Know Both.',
    whyNow: "The teenage years for girls involve hormonal changes, menstrual health, iron loss, bone development, and the foundation of lifelong wellbeing. This package is specifically designed to monitor hormones, check for anaemia (extremely common in teen girls), and ensure healthy development.",
    targetedMessage: "Your body is going through so much — periods, hormones, growth, school stress, and all the feels. This test checks your hormones (LH, FSH, Prolactin), your iron (because periods cause iron loss), your thyroid (which controls literally everything), and your vitamins. It's like a full-body check-in, done at home.",
    funFacts: [
      { emoji: '💉', fact: 'Iron deficiency anaemia affects 67% of Indian teenage girls due to menstruation' },
      { emoji: '🦋', fact: 'Thyroid disorders start in the teen years — affects weight, skin, and mood' },
      { emoji: '🌸', fact: 'Hormonal imbalances (PCOS) often begin in teens — caught early here' },
      { emoji: '🧠', fact: 'B12 deficiency affects concentration and memory — common in vegetarian teens' },
    ],
    profiles: [
      { name: 'Hormonal Profile (LH, FSH, Prolactin)', tests: 3, icon: '🌸', why: 'Key hormones for menstrual health, PCOS screening, and reproductive wellness' },
      { name: 'Thyroid Stimulating Hormone (TSH)', tests: 1, icon: '🦋', why: 'Thyroid controls weight, energy, skin, hair, and mood — critical for teen girls' },
      { name: 'Diabetes Screening (Glucose + HbA1c)', tests: 2, icon: '🍬', why: 'PCOS links strongly to insulin resistance — early screening essential' },
      { name: 'Heart Risk Profile (Lipid)', tests: 9, icon: '❤️', why: 'Heart health foundation starts in teenage years with diet and activity' },
      { name: 'Liver Function Test (LFT)', tests: 12, icon: '🫀', why: 'Oral contraceptives and supplements affect liver — baseline check important' },
      { name: 'Kidney Function Test (Basic)', tests: 6, icon: '🫘', why: 'UTIs are common in teen girls — early kidney health monitoring' },
      { name: 'Complete Blood Count (CBC)', tests: 25, icon: '🔴', why: 'Essential for detecting iron deficiency anaemia from menstrual blood loss' },
      { name: 'Iron Studies (Anaemia Screen)', tests: 5, icon: '🩸', why: 'The most comprehensive anaemia screen — critical for menstruating teen girls' },
      { name: 'Vital Vitamins (D & B12)', tests: 2, icon: '☀️', why: 'D for bone development; B12 for energy and brain health' },
      { name: 'Electrolyte Profile', tests: 4, icon: '⚡', why: 'Sodium and potassium balance — affected by diet and exercise habits' },
      { name: 'Healthy Bone Profile', tests: 3, icon: '🦴', why: 'Girls reach peak bone density by 18 — this is the critical window' },
      { name: 'Insulin Fasting + Folate', tests: 2, icon: '💉', why: 'PCOS link to insulin resistance; folate for cell health and mood' },
      { name: 'Urine Analysis (CUE)', tests: 20, icon: '💧', why: 'UTIs are 50x more common in girls — comprehensive screen here' },
    ],
    symptoms: ['Irregular periods', 'Heavy bleeding', 'Fatigue', 'Skin breakouts', 'Hair loss', 'Mood swings'],
    cta: 'Know Your Body Better',
  },
  {
    slug: 'kids-health-package',
    id: 7, name: 'Kids Health Package', emoji: '🌈',
    tagline: 'Happy Kids. Healthy Kids. Sorted.',
    ageGroup: '5 to 12 Years', gender: 'kids', tests: 60,
    market: 5000, offer: 1299, savings: 3701,
    color: '#06b6d4', gradFrom: '#06b6d4', gradTo: '#0891b2',
    badge: 'FOR KIDS',
    heroLine: 'Give Your Child the Best Start in Life.',
    whyNow: "Ages 5-12 are critical for growth, immunity, brain development, and building healthy habits. Nutritional deficiencies in this age group can affect height, intelligence, concentration, and immunity — often without obvious symptoms. This package screens everything that matters for a growing child.",
    targetedMessage: "Is your child always tired? Getting sick often? Not growing as fast as their friends? Struggling to focus in school? This simple 60-test package checks blood sugar, anaemia, vitamins, bone health, and kidneys — catching problems early when they're easy to fix.",
    funFacts: [
      { emoji: '🌱', fact: '1 in 2 Indian children has Vitamin D deficiency — causing weak bones and low immunity' },
      { emoji: '🧠', fact: 'Iron deficiency reduces IQ by up to 8 points in growing children' },
      { emoji: '😴', fact: 'Anaemia is the #1 reason children feel tired and can\'t concentrate in school' },
      { emoji: '📏', fact: 'Calcium deficiency in childhood causes permanently shorter height' },
    ],
    profiles: [
      { name: 'Diabetes Screening (Glucose + HbA1c)', tests: 2, icon: '🍬', why: 'Type 1 diabetes often starts in childhood — early detection is life-saving' },
      { name: 'Complete Blood Count (CBC)', tests: 25, icon: '🔴', why: 'Anaemia, infections, and immune health — the most important test for kids' },
      { name: 'Complete Urine Routine (CUE)', tests: 20, icon: '💧', why: 'UTIs and kidney issues in children — essential screen every year' },
      { name: 'Iron Studies (Anaemia Screen)', tests: 5, icon: '🩸', why: 'Iron deficiency affects 50% of Indian children — impacts brain and growth' },
      { name: 'Vital Vitamins (D & B12)', tests: 2, icon: '☀️', why: 'D for bone growth; B12 for brain development — both deficient in most kids' },
      { name: 'Healthy Bone Profile', tests: 3, icon: '🦴', why: 'Calcium and phosphorus levels — critical for healthy bone development' },
      { name: 'Folate / Vitamin B9', tests: 1, icon: '🌿', why: 'Essential for DNA synthesis, cell division, and brain development' },
    ],
    symptoms: ['Always tired', 'Frequent colds', 'Poor concentration', 'Slow growth', 'Pale skin', 'Loss of appetite'],
    cta: 'Keep Your Child Healthy',
  },
  {
    slug: 'family-bundle',
    id: 8, name: 'Family Bundle', emoji: '👨‍👩‍👧‍👦',
    tagline: 'One Family. One Decision. Complete Health.',
    ageGroup: 'Whole Family', gender: 'all', tests: 500,
    market: 45000, offer: 9999, savings: 35001,
    color: '#1B4D3E', gradFrom: '#1B4D3E', gradTo: '#2d6b60',
    badge: '🔥 BEST DEAL',
    heroLine: 'The Greatest Investment You\'ll Ever Make is in Your Family\'s Health.',
    whyNow: "One booking. One home visit. All 9 packages for every member of your family — from the kids (5-12) to the teens (boys & girls) to the adults (20-34) to the working members (35-60) to the couple (Male + Female combined). Total 500+ tests. Total savings ₹35,000+.",
    targetedMessage: "Stop booking tests one by one. Get the whole family done in one go. Our phlebotomist visits your home, collects samples from every family member, and you get AI-powered reports for everyone within 24 hours. Valid for 12 months — book anytime.",
    funFacts: [
      { emoji: '💰', fact: 'At ₹9,999 for the whole family, that\'s less than ₹10,000 for 500+ tests — incredible value' },
      { emoji: '🏠', fact: 'One home visit for the whole family — no hospital queues, no separate bookings' },
      { emoji: '📱', fact: 'All family members get individual AI-powered report summaries on their phones' },
      { emoji: '🎁', fact: 'Valid for 12 months — the perfect family health gift for any occasion' },
    ],
    profiles: [
      { name: 'Basic Health Checkup (All Ages)', tests: 84, icon: '🌱', why: 'Complete baseline health screen for every family member' },
      { name: 'Complete Health Checkup (Adults 20-34)', tests: 89, icon: '⚡', why: 'Full organ and diabetes screening for young adults in the family' },
      { name: 'Male Health Package (Men 35-60)', tests: 112, icon: '💪', why: '112-test comprehensive package for working men in the family' },
      { name: 'Female Health Package (Women 35-60)', tests: 112, icon: '🌸', why: '112-test package including hormonal and cancer screening for women' },
      { name: 'Couple Health Package (224 Tests)', tests: 224, icon: '💑', why: 'Combined male + female package — all 224 tests for the couple' },
      { name: 'Teen Boys Package (13-19)', tests: 96, icon: '🏃', why: 'Hormonal, growth, and lifestyle screening for teenage boys' },
      { name: 'Teen Girls Package (13-19)', tests: 96, icon: '🌺', why: 'Hormonal, iron, and reproductive health screening for teen girls' },
      { name: 'Kids Health Package (5-12)', tests: 60, icon: '🌈', why: 'Growth, immunity, and nutrition screening for children' },
      { name: 'Priority Home Collection — All Members', tests: 0, icon: '🏠', why: 'Single visit, all family members, maximum convenience' },
      { name: 'AI Report Summary — All Members', tests: 0, icon: '🤖', why: 'Individual plain-language AI reports for every family member' },
      { name: 'Dedicated Health Advisor', tests: 0, icon: '👨‍⚕️', why: 'Personal health advisor to explain results and next steps' },
      { name: 'Valid for 12 Months', tests: 0, icon: '📅', why: 'Book now, schedule the collection at your convenience' },
    ],
    symptoms: ['Family health planning', 'Preventive care', 'Annual checkup', 'Complete peace of mind'],
    cta: 'Book for the Whole Family',
  },
];
